### ISSUE TITLE
Problem with CALENDAR_EVENT

### ISSUE THREAD

**Issue by Marcin-Stan** [dlemmermann/CalendarFX#130] opened 2021-05-09 21:11 UTC
Hello,
I have problem with calendar_event. I would like to update everytime on the database side when i change interval in entry, it works well, but unfortunately when i entered to EntryDetailsView, event ENTRY_INTERVAL_CHANGED is performed several times.  I post a 40-second video, it shows the problem. [video](https://streamable.com/95it60)
The recording was made on the project: [CalendarFXApp](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/tree/master-11/CalendarFXApp)
My code:

```
EventHandler<CalendarEvent> handler = new EventHandler<CalendarEvent>() {
            @Override
            public void handle(CalendarEvent calendarEvent) {
                ScheduleEntry scheduleEntry = (ScheduleEntry) calendarEvent.getEntry();
          
                if(calendarEvent.getEventType().equals(CalendarEvent.ENTRY_INTERVAL_CHANGED)){
                    ScheduleEntity scheduleEntityTemp = scheduleEntry.getScheduleEntity();
                    scheduleEntityTemp.setStartDate(scheduleEntry.getStartDate());
                    scheduleEntityTemp.setEndDate(scheduleEntry.getEndDate());
                    scheduleEntityTemp.setTimeFrom(scheduleEntry.getStartTime());
                    scheduleEntityTemp.setTimeTo(scheduleEntry.getEndTime());
                    scheduleEntityCRUD.update(scheduleEntityTemp,false);

                }

            }
```

**Comment by dlemmermann** [comment] 2022-07-20 16:15
This has been fixed as part of the fix for #152 "EntryDetailsView modifies the calendar entry when loading new time interval." So #152 was actually a duplicate of your issue.

**Closed as completed by dlemmermann** 2022-07-20 16:15 UTC
