### ISSUE TITLE
I can't set the Calendars' visibility in the initialize method

### ISSUE THREAD

**Issue by e-magon** [dlemmermann/CalendarFX#98] opened 2020-07-06 18:01 UTC
I'd like to know if there is a way to have a calendar hidden by default when starting the application.

I made a button that, when clicked, do these things:

1. It reads from the database the list of calendars to be hidden;
2. It access the CalendarView component in the window;
3. It gets the SourceView of the CalendarView;
4. It calls the setCalendarVisibility according to the data read form the database.

The button works as expected.

The problem starts when I try to do these things in the `initialize` method: when the window will eventually show up, the Calendars will all be visible. I even tried to make a thread that waits 5 seconds and then hides the calendars (to be sure that it does it after the window finished loading) but the program throws an Exception:

`Exception in thread "Calendar: Update Calendar Visibility" java.lang.IllegalStateException: Not on FX application thread; currentThread = Calendar: Update Calendar Visibility`

Is there a way to wait for the window to finish loading and then hide the calendars accordingly?

Thank you

EDIT: I solved this problem by using the `stage.setOnShown(EventHandler<WindowEvent> value)` method before showing the stage.
It works, but I'd like to know if there is another way to tell the program what to do after loading the window (maybe in the `initialize` method)

**Comment by dlemmermann** [comment] 2020-08-19 13:25
Could you please add a standalone example to this ticket that reproduces the issue? Once I have this file I will work on this ticket ASAP.

**Comment by dlemmermann** [comment] 2021-03-22 10:32
Closing due to missing activity.

**Closed as completed by dlemmermann** 2021-03-22 10:32 UTC
Labels: needs example
